"""Initial schema

Revision ID: dee7013ca439
Revises: 
Create Date: 2025-10-06 18:11:58.135303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee7013ca439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('active_round_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_api_key'), 'players', ['api_key'], unique=True)
    op.create_table('prompts',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_copy_quality', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('rounds',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('prompt_text', sa.String(length=500), nullable=True),
    sa.Column('submitted_word', sa.String(length=15), nullable=True),
    sa.Column('prompt_round_id', sa.UUID(), nullable=True),
    sa.Column('original_word', sa.String(length=15), nullable=True),
    sa.Column('copy_word', sa.String(length=15), nullable=True),
    sa.Column('system_contribution', sa.Integer(), nullable=False),
    sa.Column('wordset_id', sa.UUID(), nullable=True),
    sa.Column('vote_submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt_id'], ),
    sa.ForeignKeyConstraint(['prompt_round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_index(op.f('ix_rounds_created_at'), 'rounds', ['created_at'], unique=False)
    op.create_index(op.f('ix_rounds_expires_at'), 'rounds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_rounds_player_id'), 'rounds', ['player_id'], unique=False)
    op.create_index(op.f('ix_rounds_prompt_round_id'), 'rounds', ['prompt_round_id'], unique=False)
    op.create_index('ix_rounds_status_created', 'rounds', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_rounds_wordset_id'), 'rounds', ['wordset_id'], unique=False)
    op.create_table('wordsets',
    sa.Column('wordset_id', sa.UUID(), nullable=False),
    sa.Column('prompt_round_id', sa.UUID(), nullable=False),
    sa.Column('copy_round_1_id', sa.UUID(), nullable=False),
    sa.Column('copy_round_2_id', sa.UUID(), nullable=False),
    sa.Column('prompt_text', sa.String(length=500), nullable=False),
    sa.Column('original_word', sa.String(length=15), nullable=False),
    sa.Column('copy_word_1', sa.String(length=15), nullable=False),
    sa.Column('copy_word_2', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('third_vote_at', sa.DateTime(), nullable=True),
    sa.Column('fifth_vote_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('total_pool', sa.Integer(), nullable=False),
    sa.Column('system_contribution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copy_round_1_id'], ['rounds.round_id'], ),
    sa.ForeignKeyConstraint(['copy_round_2_id'], ['rounds.round_id'], ),
    sa.ForeignKeyConstraint(['prompt_round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('wordset_id')
    )
    op.create_index(op.f('ix_wordsets_fifth_vote_at'), 'wordsets', ['fifth_vote_at'], unique=False)
    op.create_index(op.f('ix_wordsets_prompt_round_id'), 'wordsets', ['prompt_round_id'], unique=False)
    op.create_index('ix_wordsets_status_vote_count', 'wordsets', ['status', 'vote_count'], unique=False)
    op.create_table('daily_bonuses',
    sa.Column('bonus_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('bonus_id'),
    sa.UniqueConstraint('player_id', 'date', name='uq_player_daily_bonus')
    )
    op.create_index(op.f('ix_daily_bonuses_date'), 'daily_bonuses', ['date'], unique=False)
    op.create_index(op.f('ix_daily_bonuses_player_id'), 'daily_bonuses', ['player_id'], unique=False)
    op.create_table('player_abandoned_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('prompt_round_id', sa.UUID(), nullable=False),
    sa.Column('abandoned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['prompt_round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'prompt_round_id', name='uq_player_abandoned_prompt')
    )
    op.create_index(op.f('ix_player_abandoned_prompts_player_id'), 'player_abandoned_prompts', ['player_id'], unique=False)
    op.create_table('result_views',
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('wordset_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('payout_collected', sa.Boolean(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['wordset_id'], ['wordsets.wordset_id'], ),
    sa.PrimaryKeyConstraint('view_id'),
    sa.UniqueConstraint('player_id', 'wordset_id', name='uq_player_wordset_result')
    )
    op.create_index(op.f('ix_result_views_payout_collected'), 'result_views', ['payout_collected'], unique=False)
    op.create_index(op.f('ix_result_views_player_id'), 'result_views', ['player_id'], unique=False)
    op.create_index(op.f('ix_result_views_wordset_id'), 'result_views', ['wordset_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_player_created', 'transactions', ['player_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_player_id'), 'transactions', ['player_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_table('votes',
    sa.Column('vote_id', sa.UUID(), nullable=False),
    sa.Column('wordset_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('voted_word', sa.String(length=15), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('payout', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['wordset_id'], ['wordsets.wordset_id'], ),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('player_id', 'wordset_id', name='uq_player_wordset_vote')
    )
    op.create_index(op.f('ix_votes_created_at'), 'votes', ['created_at'], unique=False)
    op.create_index(op.f('ix_votes_player_id'), 'votes', ['player_id'], unique=False)
    op.create_index(op.f('ix_votes_wordset_id'), 'votes', ['wordset_id'], unique=False)
    op.create_foreign_key('fk_players_active_round_id', 'players', 'rounds', ['active_round_id'], ['round_id'], ondelete='SET NULL')
    op.create_foreign_key('fk_rounds_wordset_id', 'rounds', 'wordsets', ['wordset_id'], ['wordset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rounds_wordset_id', 'rounds', type_='foreignkey')
    op.drop_constraint('fk_players_active_round_id', 'players', type_='foreignkey')
    op.drop_index(op.f('ix_votes_wordset_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_player_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_created_at'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_player_id'), table_name='transactions')
    op.drop_index('ix_transactions_player_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_result_views_wordset_id'), table_name='result_views')
    op.drop_index(op.f('ix_result_views_player_id'), table_name='result_views')
    op.drop_index(op.f('ix_result_views_payout_collected'), table_name='result_views')
    op.drop_table('result_views')
    op.drop_index(op.f('ix_player_abandoned_prompts_player_id'), table_name='player_abandoned_prompts')
    op.drop_table('player_abandoned_prompts')
    op.drop_index(op.f('ix_daily_bonuses_player_id'), table_name='daily_bonuses')
    op.drop_index(op.f('ix_daily_bonuses_date'), table_name='daily_bonuses')
    op.drop_table('daily_bonuses')
    op.drop_index('ix_wordsets_status_vote_count', table_name='wordsets')
    op.drop_index(op.f('ix_wordsets_prompt_round_id'), table_name='wordsets')
    op.drop_index(op.f('ix_wordsets_fifth_vote_at'), table_name='wordsets')
    op.drop_table('wordsets')
    op.drop_index(op.f('ix_rounds_wordset_id'), table_name='rounds')
    op.drop_index('ix_rounds_status_created', table_name='rounds')
    op.drop_index(op.f('ix_rounds_prompt_round_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_player_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_expires_at'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_created_at'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_players_api_key'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
